server:
  port: 10400
  servlet:
    contextPath: /auth

spring:
  config:
    import: optional:classpath:application-core.yml
  application:
    name: auth

oauth2:
  kakao:
    infoUrl: https://kapi.kakao.com
    baseUrl: https://kauth.kakao.com
    clientId: c32cb7f8f1af792829701b7bbd4e5b7f
    redirectUri: https://dev-poom.c0dewave.com/auth
    secretKey: sOTe7SjI0edhG9pfqYsbF8FLcexbAkpZ

# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server.luckytree-zwsm.svc.cluster.local:8761/eureka


# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
