server:
  port: 10400
  servlet:
    contextPath: /auth

spring:
  config:
    import: optional:classpath:application-core.yml

oauth2:
  kakao:
    infoUrl: https://kapi.kakao.com
    baseUrl: https://kauth.kakao.com
    clientId: c32cb7f8f1af792829701b7bbd4e5b7f
    redirectUri: https://dev-poom.c0dewave.com/auth
    secretKey: sOTe7SjI0edhG9pfqYsbF8FLcexbAkpZ

feign:
  member: http://192.168.0.123:10100/member
