spring:
  application:
    name: member-service
  profiles:
    active: develop
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: member, actuator, auth, redis
      label: local
      profile: local
server:
  port: 10100