spring:
  application:
    name: member-service
  profiles:
    active: main
  config:
    import: "optional:configserver:http://192.168.0.14:31185/"
  cloud:
    config:
      name: mysql, eureka, actuator, auth
      label: develop
      profile: develop
server:
  port: 10100

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400