spring:
  application:
    name: member-service
  profiles:
    active: develop
  config:
    #import: "optional:configserver:http://192.168.0.14:31185/"
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: member, actuator, auth, redistest
      label: local
      profile: local
server:
  port: 10100